InhouseMembership/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InhouseMembership.Data;
using InhouseMembership.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace InhouseMembership.Controllers
{
    [Authorize(Roles = "Admin, Coach, Member")]
    public class ScheduleController : Controller
    {
        private readonly ApplicationDbContext _context;
        UserManager<ApplicationUser> _userManager;

        
        public ScheduleController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }



        // GET: Schedule
        [Authorize(Roles = "Admin, Coach, Member")]
        public async Task<IActionResult> Index()
        {

            var scheduleList = await _context.Schedules.ToListAsync();
                 
            // ensure the coach logged in can only see the upcoming schedule that is hosted by himself
            if (User.IsInRole("Coach"))
            {
                return View(scheduleList.Where(s => s.CoachId.Equals(_userManager.GetUserId(HttpContext.User))));
            }
            // members and admins can see all schedules
            else {
                return View(scheduleList);
            }        
        }


        // GET: Schedule/Details/5
        [Authorize(Roles = "Admin, Coach, Member")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules
                .FirstOrDefaultAsync(m => m.ScheduleId == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }


        // redirect to the coach profile page, it is used to access to a coach profile from the schedule detail page
        [Authorize(Roles = "Admin, Coach, Member")]
        public IActionResult CoachProfile(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // get the coach profile id based on the coach id passed in the function
            CoachProfile coachProfile = _context.CoachProfiles.Where(p => p.CoachId == id).FirstOrDefault();

            if (coachProfile == null)
            {
                return RedirectToAction("NoProfile", "CoachProfile");
            }
            var profileId = coachProfile.CoachProfileId;
        
            // redirect to the profile page using the profile id
            return Redirect("../../CoachProfile/Details/" + profileId);
        }


        // Enroll in a schedule
        [Authorize(Roles = "Admin, Member")]
        public IActionResult CreateEnrollment(string id)
        {
            // generate random enrollment Id
            Random rnd = new Random();
            int randomNumber = rnd.Next();
            string strRandomNumber = randomNumber.ToString();
            // the data will be passed to the create action in 'Enrollment' controller using TempData to create a new enrollment
            var data = new Dictionary<string, string>() {         
            {"EnrollmentId", strRandomNumber},
            {"ScheduleId", id},
            {"MemberId", _userManager.GetUserAsync(User).Result.Id},
            //{"Enrollments", _userManager.GetUserAsync(User).Result},
            };
            TempData["mydata"] = data;
            //TempData["mydata"] = JsonConvert.SerializeObject(data);
            return RedirectToAction("Create", "Enrollment");

        }


        // GET: Schedule/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            // pass a list of coaches to ViewData, which can be used to Create a dropdown select menu for matching coach and schedule 
            ViewData["coaches"] = _userManager.GetUsersInRoleAsync("Coach").Result.ToList();
            return View();
        }

        // POST: Schedule/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ScheduleId,CoachId,EventName,EventDate,Location")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                // generate random Schedule Id
                Random rnd = new Random();
                int randomNumber = rnd.Next();
                string strRandomNumber = randomNumber.ToString();
                schedule.ScheduleId = strRandomNumber;
                _context.Add(schedule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schedule);
        }


        // GET: Schedule/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }
            return View(schedule);
        }




        // POST: Schedule/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("ScheduleId,CoachId,EventName,EventDate,Location")] Schedule schedule)
        {
            if (id != schedule.ScheduleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schedule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleExists(schedule.ScheduleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schedule);
        }

 
        
        // GET: Schedule/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules
                .FirstOrDefaultAsync(m => m.ScheduleId == id);

            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedule/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var schedule = await _context.Schedules.FindAsync(id);
            _context.Schedules.Remove(schedule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleExists(string id)
        {
            return _context.Schedules.Any(e => e.ScheduleId == id);
        }
    }
}

InhouseMembership/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InhouseMembership.Data;
using InhouseMembership.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace InhouseMembership.Controllers
{
    [Authorize(Roles = "Admin, Member")]
    public class UserController : Controller
    {

        UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        public UserController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }


        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> GetAdmins()
        {
            // get a list of admins
            var admins = await _userManager.GetUsersInRoleAsync("Admin");

            // pass the admins to Index view page
            return View("Index", admins);
        }


        [Authorize(Roles = "Admin, Member")]
        public async Task<ActionResult> GetCoaches()
        {
            // get a list of coaches
            var coaches = await _userManager.GetUsersInRoleAsync("Coach");

            // pass the coaches to Index view page
            return View("Index", coaches);
            
        }



        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> GetMembers()
        {
            // get a list of members
            var members = await _userManager.GetUsersInRoleAsync("Member");

            // pass the members to Index view page
            return View("Index", members);

        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return Redirect("../Identity/Account/Register");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
                //.FirstOrDefaultAsync(m => m.ScheduleId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }


        [Authorize(Roles = "Admin, Member")]
        // redirect to the coach profile page
        public IActionResult CoachProfile(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // get the coach profile id based on the coach id passed into the function
            CoachProfile coachProfile = _context.CoachProfiles.Where(p => p.CoachId == id).FirstOrDefault();

            if (coachProfile == null)
            {
                
                return RedirectToAction("NoProfile", "CoachProfile");

            }
            var profileId = coachProfile.CoachProfileId;


            // redirect to the profile page using the profile id
            return Redirect("../../CoachProfile/Details/" + profileId);
        }



        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var User = await _userManager.FindByIdAsync(id);
            Console.WriteLine("User: " + User);
            if (User == null)
            {
                return NotFound();
            }
            return View(User);
        }

        // POST: Enrollment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,Email, PhoneNumber")] ApplicationUser applicationUser)
        {
            
            if (ModelState.IsValid)
            {

                ApplicationUser user = new ApplicationUser();
                user = _userManager.FindByIdAsync(id).Result;
                await _userManager.SetUserNameAsync(user, applicationUser.UserName);
                await _userManager.SetEmailAsync(user, applicationUser.Email);
                await _userManager.SetPhoneNumberAsync(user, applicationUser.PhoneNumber);
                var userRole = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
                // check the role of the user that is being deleted, then retrun differnet list accordingly

                if (userRole == "Admin")
                {
                    return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Admin"));
                }
                else if (userRole == "Coach")
                {

                    return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Coach"));

                }
                else if (userRole == "Member")
                {

                    return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Member"));
                }




                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            ApplicationUser user = new ApplicationUser();
            user = _userManager.FindByIdAsync(id).Result;
            var userRole = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            await _userManager.DeleteAsync(user);
            // check the role of the user that is being deleted, then retrun differnet list accordingly

            if (userRole == "Admin")
            {
                return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Admin"));
            }
            else if (userRole == "Coach")
            {
                return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Coach"));

            }
            else if (userRole == "Member")
            {
                return View(nameof(Index), await _userManager.GetUsersInRoleAsync("Member"));
            }



            return RedirectToAction(nameof(Schedule));

        }
    }
}

InhouseMembership/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InhouseMembership</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InhouseMembership</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <!-- if the user is admin, show schedules, admins, coaches, members and enrollments at the navigation bar -->
                        @if (User.IsInRole("Admin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Schedules</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetAdmins">Admins</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetCoaches">Coaches</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetMembers">Members</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment" asp-action="Index">Enrollments</a>
                            </li>

                        }

                        else if (User.IsInRole("Coach"))
                        {
                            <!-- if the user is a coach, show the options to CRUD his own profile, and see upcoming schedules that is hosted by himself and enrolled members to those evets -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoachProfile" asp-action="Details">My Profile</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Upcoming Schedule</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment" asp-action="Index">Enrolled Members</a>
                            </li>

                        }

                        else if (User.IsInRole("Member"))
                        {
                            <!-- if the user is a member, shwo a list of schedules that they can enroll, as well as a list of coache profiles -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Schedule</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoachProfile" asp-action="Index">Coache Profiles</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InhouseMembership - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>